;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} convex.shell.-requirer
  (:require
    #?(:clj convex.shell)
    #?(:clj convex.shell.ctx)
    #?(:clj convex.shell.dep)
    #?(:clj convex.shell.dep.fail)
    #?(:clj convex.shell.dep.git)
    #?(:clj convex.shell.dep.local)
    #?(:clj convex.shell.dep.relative)
    #?(:clj convex.shell.fail)
    #?(:clj convex.shell.flow)
    #?(:clj convex.shell.io)
    #?(:clj convex.shell.log)
    #?(:clj convex.shell.project)
    #?(:clj convex.shell.req)
    #?(:clj convex.shell.req.account)
    #?(:clj convex.shell.req.bench)
    #?(:clj convex.shell.req.db)
    #?(:clj convex.shell.req.dep)
    #?(:clj convex.shell.req.dev)
    #?(:clj convex.shell.req.file)
    #?(:clj convex.shell.req.fs)
    #?(:clj convex.shell.req.juice)
    #?(:clj convex.shell.req.log)
    #?(:clj convex.shell.req.reader)
    #?(:clj convex.shell.req.state)
    #?(:clj convex.shell.req.str)
    #?(:clj convex.shell.req.stream)
    #?(:clj convex.shell.req.sys)
    #?(:clj convex.shell.req.time)
    #?(:clj convex.shell.time)
))


;;;;;;;;;;


(defn -main [& _arg+])
