(ns convex.lisp.test.core.pred

  "Tests Convex core type predicate. 
  
   Specialized predicates such as `contains-key?` or `fn?` are located in relevant namespace."

  {:author "Adam Helinski"}

  (:require [clojure.test                  :as t]
            [clojure.test.check.generators :as TC.gen]
            [clojure.test.check.properties :as TC.prop]
            [convex.lisp.form              :as $.form]
            [convex.lisp.gen               :as $.gen]
            [convex.lisp.test.eval         :as $.test.eval]
            [convex.lisp.test.prop         :as $.test.prop]))


;;;;;;;;;;


(defn- -prop

  ;; Used by [[pred-data-false]] and [[pred-data-true]].

  [form result? f gen]

  (TC.prop/for-all [x gen]
    (let [result ($.test.eval/result* (~form ~x))]

      ($.test.prop/mult*

        "Returns right boolean value"
        (result? result)
        
        "Consistent with Clojure"
        (if f
          (= result
             (f x))
          true)))))



(defn prop-false

  "Like [[pred-data-true]] but tests for negative results."


  ([form gen]

   (prop-false form
               nil
               gen))


  ([form f gen]

   (-prop form
          false?
          f
          gen)))



(defn prop-true

  "Tests if a value generated by `gen` passes a data predicate on the CVM.
  
   If `f-clojure` is given, also ensures that the very same value produces the exact same result
   in Clojure."


  ([form gen]

   (prop-true form
              nil
              gen))


  ([form f gen]

   (-prop form
          true?
          f
          gen)))


;;;;;;;;;;


($.test.prop/deftest account?--false

  (prop-false 'account?
              (TC.gen/such-that (comp not
                                      $.form/address?)
                                $.gen/any)))



($.test.prop/deftest address?--false

  (prop-false 'address?
              (TC.gen/such-that (comp not
                                      $.form/address?)
                                $.gen/any)))



($.test.prop/deftest address?--true

  (TC.prop/for-all* [$.gen/address]
                    #($.test.eval/result (list 'address?
                                               %))))



($.test.prop/deftest blob?--false

  (prop-false 'blob?
              (TC.gen/such-that (comp not
                                      $.form/blob?)
                                $.gen/any)))



($.test.prop/deftest blob?--true

  (prop-true 'blob?
             $.gen/blob))



($.test.prop/deftest boolean?--false

  (prop-false 'boolean?
              boolean?
              (TC.gen/such-that (comp not
                                      boolean?)
                                $.gen/any)))



(t/deftest boolean?--true

  (t/is (true? ($.test.eval/result true))
        "True")

  (t/is (false? ($.test.eval/result false))
        "False"))



#_($.test.prop/deftest coll?--false

  ;; TODO. Returns true on blob-like items.

  (prop-false 'coll?
              coll?
              $.gen/scalar))



($.test.prop/deftest coll?--true

  (prop-true 'coll?
             coll?
             $.gen/collection))



($.test.prop/deftest keyword?--false

  (prop-false 'keyword?
              keyword?
              (TC.gen/such-that (comp not
                                      keyword?)
                                $.gen/any)))



($.test.prop/deftest keyword?--true

  (prop-true 'keyword?
             keyword?
             $.gen/keyword))



($.test.prop/deftest list?--false

  (prop-false 'list?
              $.form/list?
              (TC.gen/such-that (comp not
                                      $.form/list?)
                                $.gen/any)))



($.test.prop/deftest list?--true

  (prop-true 'list?
             $.form/list?
             $.gen/list))



($.test.prop/deftest long?--false

  (prop-false 'long?
              int?
              (TC.gen/such-that (comp not
                                      int?)
                                $.gen/any)))



($.test.prop/deftest long?--true

  (prop-true 'long?
             int?
             $.gen/long))



($.test.prop/deftest map?--false

  (prop-false 'map?
              map?
              (TC.gen/such-that #(not (map? %))
                                $.gen/any)))



($.test.prop/deftest map?--true

  (prop-true 'map?
             map?
             $.gen/map))



($.test.prop/deftest nil?--false

  (prop-false 'nil?
              nil?
              (TC.gen/such-that some?
                                $.gen/any)))



(t/deftest nil?--true

  (t/is (true? (nil? ($.test.eval/result nil))))

  (t/is (true? (nil? ($.test.eval/result '(do nil))))))



($.test.prop/deftest number?--false

  (prop-false 'number?
              number?
              (TC.gen/such-that (comp not
                                      number?)
                                $.gen/any)))



($.test.prop/deftest number?--true

  (prop-true 'number?
             number?
             $.gen/number))



($.test.prop/deftest set?--false

  (prop-false 'set?
              set?
              (TC.gen/such-that (comp not
                                      set?)
                                $.gen/any)))



($.test.prop/deftest set?--true

  (prop-true 'set?
             set?
             $.gen/set))



($.test.prop/deftest str?--false

  (prop-false 'str?
              string?
              (TC.gen/such-that (comp not
                                      string?)
                                $.gen/any)))



($.test.prop/deftest str?--true

  (prop-true 'str?
             string?
             $.gen/string))



($.test.prop/deftest symbol?--false

  (prop-false 'symbol?
              (TC.gen/such-that (comp not
                                      $.form/quoted?)
                                $.gen/any)))



($.test.prop/deftest symbol?--true

  (prop-true 'symbol?
             $.gen/symbol-quoted))



($.test.prop/deftest vector?--false

  (prop-false 'vector?
              vector?
              (TC.gen/such-that (comp not
                                      vector?)
                                $.gen/any)))



($.test.prop/deftest vector?--true

  (prop-true 'vector?
             vector?
             $.gen/vector))
